server.port: 8080

---
spring:
  config:
    activate:
      on-profile:
      - staging
server.port: 80
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true