apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app.kubernetes.io/name: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: products
  template:
    metadata:
      labels:
        app.kubernetes.io/name: products
    spec:
      containers:
        - name: products
          image: syriail/commerce-products:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "staging"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1