apiVersion: v1
kind: Service
metadata:
  name: products-svc
  labels:
    app.kubernetes.io/name: products
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: products
    